src/videojs.ads.js
test/videojs.ads.test.js

Also remove play() call on timeout since this is now handled in the same way and was causing play() to be invoked twice.

Ensure that playback is resumed when in content-playback state if a play event was canceled earlier.

---

src/videojs.ads.js
test/videojs.ads.test.js

Only trigger ended from content-resuming if we don't get a native ended event.
Still requires:

Trigger ended from content-resuming on ended

---

example/index.html
src/videojs.ads.js
test/ads.html

Previously, event.stopImmediatePropagation was used on redispatched
events but that was causing issues because the actual native events were
getting stopped in addition to the player events. Updated to stop
immediate propagation manually so only the player events will stop.
The changes to stopImmediatePropagation mean that this cannot be used
with the google closure compiled version of videojs.
Also, tryToResume now checks the video element's readyState for trying
to resume. Fixes #46. Android devices in particular fail to have a
seekable property after reloading a video, especially, with HLS
content.

Don't stop propagation on video element events.

---

README.md
src/videojs.ads.js
test/videojs.ads.test.js

Having a skipLinearAdMode method which triggers an 'adskip' event will allow plugin developers to quickly skip the preroll flow and move directly to content-playback when they:
* Already know they don't have a preroll to play
* There are no preroll ads returned in the ad response
* There are only non-linear ads returned in the ad response.
RIght now, some plugins work around this deficiency by triggering adserror or adstimeout events.  This allows for a more semantically correct transition.

Add skipLinearAdMode and 'adskip' event handling.

---

src/videojs.ads.js
test/videojs.ads.test.js

Use the ad-playback state to make adstart and adend trigger more accurately. Remove duplicate code around triggering adstart state that is already included in the ad-playback.enter().

Adstart adend checks

---

test/videojs.ads.test.js

This test is to ensure that we do not get a regression in video.js that results in the `vjs-has-started` class not being applied during preroll ad playback.

Test that the vjs-has-started class is added once a preroll begins

---

src/videojs.ads.js

NOTE: This is for the `vjs-5-upgrade` branch only!!
Because the tech may have changed from the original video to the ad video, we need to make sure we have the correct `tech` object before attempting to resume.
Ex: The video playing is an RTMP stream using the Flash player, the video ad playing was an MP4 (so HTML5), when attempting to resume, we were setting the `tech` variable BEFORE switching the source back to the RTMP stream so the video was never resuming from where it left off.

VJS5 - resuming video tech fix

---

src/videojs.ads.js
test/videojs.ads.snapshot.js
test/videojs.ads.test.js

This dries up a lot of code that was old and no longer needed. It builds on #133.

Be More Dry

---

.travis.yml
src/videojs.ads.js
test/videojs.ads.snapshot.js

In some browsers, like firefox with MSE, canplay doesn't fire at the
correct time. So, we need to race it against a setTimeout so that we
would actually try to resume if canplay doesn't fire correctly.
In the tryToResume function we then clear out the event handler and the
timeout depending on which came back first.
Also, see https://github.com/videojs/videojs-contrib-hls/issues/469

Race canplay event with a setTimeout.

---

.npmignore

This avoids things like editor files getting included in the package.

Update .npmignore to use generator version

---

src/videojs.ads.js

This PR is to backport #133 to fix using video.js 5.0 with MSE HLS and the 4.0 to 5.0 compatibility script.

Backport fix for MSE HLS src/currentSrc

---

README.md
src/videojs.ads.js
test/videojs.ads.test.js

Related: https://github.com/videojs/video.js/pull/2957 (necessary for this to work in HLS after the src has been changed by a third party)

Fix prefixing events when player is preload none

---

package.json
src/videojs.ads.js

**Issue Description:**
When you get an empty ad, we do not properly remove the `vjs-ad-loading` class, which causes the Player to not handle the ad state correctly.
The effect of this is that the player feels it's always in ad mode.
**Fix Description:**
In the current state of things, we do not have proper logic to check for an empty ad, because of which the `vjs-ad-loading` class is not removed properly.
Currently we are removing `vjs-ad-loading` class on pre-roll, ads-ready and post-rolls, but don't have anything for empty ad. This fix should take care of that.
This fix makes sure that when we are in `endLinearAdMode` , after triggering `adend`, the `vjs-ad-loading` class is always removed.

Fix for metrics on empty ad

---

src/videojs.ads.js

**Issue:** When switching from a VOD source to a LIVE source using a playlist, the ads snapshot from the VOD remains while the live content is playing. This leaves content-playback in a weird state where timeupdate events are not passed along to the player while the LIVE content is playing - due to the fact that contrib-ads is waiting for the original video to play back.  Playback eventually fails with a PLAYER_ERR_TIMEOUT after 45 seconds of apparent inactivity even though the live video has been playing.
**Root Cause:** The check to determine if the snapshot should be cleared in the contentupdate event handler in the FSM only checks if there is a snapshot and if the snapshot has ended, ie. the content video has ended. This doesn't capture the scenario where the source changed but the …

fix check to reset snapshot on contentupdate

---

src/plugin.js
test/videojs.ads.test.js

Proposal:
This is a proposal fix for preventing content from playing in the background while an Ad is playing on an Android device within a playlist.
The current issue is that if you have an auto-advance playlist containing HLS videos, the duration of the video when the Ad starts is given as Infinity erroneously on Android devices(I have tested this on v5.x and v6.x), and the content does not stop when a pre-roll is playing.
The idea is to pause playback of the content before we signal the ad plugin to play a pre-roll.

Fix for content-play behind ad on Android

---

src/cancelContentPlay.js

This import was probably forgotten. In most situations where videojs is available in the global scope this wouldn't have resulted in any issues, but when packaging everything with Webpack or Browserify this is not always the case.
Because of this bug using videojs-contrib-ads with Webpack currently breaks. A patch release would be much appreciated!

Add import of videojs in cancelContentPlay.js

---

src/cancelContentPlay.js

Description: In cancelContentPlay, there is code to hide the video element and overlay a black filled div over the video player until 'adplaying', 'adtimeout', 'adserror', 'adscanceled', 'adskip', or 'playing' fires at which point the div is hidden and the video element made visible.
Existing code: This was happening in IMA3 and FW and in Chrome or Safari on the iPad. This code currently tests whether or not to run by checking videojs.browser.IS_IOS.
Proposed change: This is not sufficient as we also need to make sure it is NOT an iPad. This fix modifies the check to test for videojs.browser.IS_IOS && !videojs.browser.IS_IPAD.
Expected behavior:
1. Load video with preroll ad in browser on iPad
2. Preroll ad loads and plays, ad is visible, audio is audible
3. Content plays
Actual behavior: …

blank div to prevent content flash covers ad on iPad

---

src/cancelContentPlay.js

This fix adds a check for playsinline on iPhone to determine whether to add the black div used to cover the content player and prevent flash of content/poster.  Without this fix, a player with playsinline on an iPhone with iOS10 shows the black div over the player preventing the ad from being viewed.  
The black div would also appear on iPhones on iOS10 without playsinline - in this case, the div remains visible after returning from fullscreen during a paused ad and before content begins playing. Added a check for playsinline and the placeholder on fullscreenchange to remove the div and show the player.
To test scenario 1: 
- setup player with playsinline and ad plugin (ima3 or freewhee)
- play video on iPhone with iOS 10
Before fix: black div covers ad
After fix: black div is never …

Fix placehoder div on ios10 playsinline

---

src/cancelContentPlay.js

In some cases, the placeholder `div` on iPhone does not appear in the same position as the player.
Give the placeholder the same `position` and `top` values as the player.

Placeholder div's CSS position and top values now match the player's

---

src/plugin.js

For live videos error is thrown after ad is shown. I found [here](https://github.com/videojs/videojs-contrib-ads/blob/v3.3.13/src/videojs.ads.js#L448) that in previous version `false` was returned instead of throwing an error.

Remove error throwing for live videos.

---

src/plugin.js

Sometimes when player is disposed there is an error like this:
```js
Uncaught TypeError: Cannot read property 'vdata1495796386723' of null
at Object.hasElData (dom.js:335)
at Object.trigger (events.js:390)
at Player.trigger (component.js:816)
at plugin.js:323
```
As we can see here https://github.com/videojs/videojs-contrib-ads/blob/master/src/plugin.js#L323 when window timeouts are not cleared after dispose `video.js` could not find the reference to player to trigger the event.

Clear registered timeouts when player is disposed.

---

src/snapshot.js

This is for players which share the video element with the ad integration. This is causing problems in Chrome/Edge with Video.js 6 due to the asynchronous nature of calling player.src().

fix: Remove old call to player.load() during snapshot restoration.

---

src/plugin.js
src/snapshot.js
test/karma.conf.js
test/test.ads.js
test/test.snapshot.js

Changes include:
- now calls `snapshot. initializeSnapshot` when setting up the plugin
- now adds and removes the event handler to all platforms when creating/restoring a snapshot
- unit tests

fix: snapshot.trackChangeHandler is undefined

---

package.json
src/plugin.js

I researched the history of this code and found in a deleted comment that it was meant to address autoplay after source changes. I tested without this code in a variety of Android versions and found no issues. Further, [this code breaks videojs-ima](https://github.com/videojs/videojs-contrib-ads/issues/291). I believe it was a workaround for another bug that has since been fixed. Time to go.

remove android hack that was breaking videojs-ima

---

src/snapshot.js

When the snapshot [restores the content source](https://github.com/videojs/videojs-contrib-ads/blob/master/src/snapshot.js#L256) following ad playback, the `currentTime` is not able to be set in iOS, causing the content to restart from the beginning following midrolls. Even with `preload="auto"`, Safari loads only the video metadata, so [we do not get a `contentcanplay` player event](https://github.com/videojs/videojs-contrib-ads/blob/master/src/snapshot.js#L261) and [setting the `currentTime`](https://github.com/videojs/videojs-contrib-ads/blob/master/src/snapshot.js#L180) fails to seek the content.
`player.load()` does not seem to make the content seekable in iOS. We still only get a `contentloadedmetadata` event, and setting the `currentTime` still fails. So far, the only way I have …

fix: content restarts from the beginning when snapshot restores source after midroll in iOS

---

src/cancelContentPlay.js

The time has come to remove the placeholder div (aka The Black Div of Death) from `cancelContentPlay()`. Content flash before preroll playback in the iOS native player (the original reason for its creation) is evidently less of an issue in later versions of iOS, and this workaround has caused more problems than it has solved. The decision to remove it comes sanctioned by @incompl and @ldayananda.

Remove the placeholder div logic from cancelContentPlay()

---

src/plugin.js
src/snapshot.js
test/test.ads.js
test/test.snapshot.js

Proposed fix for [BC-38559](https://jira.brightcove.com/browse/BC-38559) and [BC-39463](https://jira.brightcove.com/browse/BC-39463).
There are 3 issues this PR addresses:
1. Text track modes are not correctly restored after ads in general. This is the result of the fact that the snapshot saves and restores both `player.textTracks()` and `player.remoteTextTracks()` separately. `player.textTracks()` contains the TextTrackList of all text tracks, so it isn't necessary to also get a snapshot of `remoteTextTracks()`. And since they both store references to the same remote text tracks, there's a bug in [this logic](https://github.com/videojs/videojs-contrib-ads/blob/master/src/snapshot.js#L49-L69) where the remote text track modes are all disabled before the second loop, so the snapshot saves …

Fix caption persistence

---

src/playMiddleware.js
src/plugin.js
test/integration/test.playMiddleware.js
test/unit/test.playMiddleware.js

This ensures that the code in playMiddleware.play does not run if another middleware terminates.

Play middleware: only trigger play event when our play middleware terminates

---

docs/integrator/snapshot.md
src/adBreak.js
src/snapshot.js
src/states/Preroll.js
test/integration/test.ads.js

When `startLinearAdMode()` is invoked, ad break starts where `removeNativePoster()` removes the poster attribute. When the ad break ends, `endLinearAdMode()` is invoked and adBreak.end(player) is called. Here, it restores the snapshot [restorePlayerSnapshot](https://github.com/videojs/videojs-contrib-ads/blob/c1f23c74f35702314b82e4d1468d29efad08dcdc/src/adBreak.js#L69) and adds the poster attribute [here](https://github.com/videojs/videojs-contrib-ads/blob/c1f23c74f35702314b82e4d1468d29efad08dcdc/src/snapshot.js#L182). Also, in videojs-ima3, it listens to the `playing` event and once again removes the poster attribute.
What happens in case of `preload:none` is, before it listens to `playing` and removes the poster attribute; there is already a flash of content(poster) as the poster …

IMA content flash after preroll  - preload none (onload)

---

src/plugin.js
src/snapshot.js

This doesn't seem to happen in practice, but it was causing tests to fail. This may have to do with tests not being cleaned up properly, but this makes the tests pass for now.

Warnings instead of errors if play promise rejected

---

src/ads.js
test/integration/test.ads.js

Make sure `shouldPlayContentBehindAd` only returns `true` for liveCuePoints

check shouldPlayContentBehindAd for live only

---

src/states/BeforePreroll.js
src/states/abstract/State.js
test/unit/states/test.BeforePreroll.js

This isn't necessary because on dispose the plugin is abandoned. It's state doesn't matter anymore because it won't be used. Any new players will have newly-initialized plugins with their initial state set correctly.

chore: Remove unneeded onDispose handling

---

src/cancelContentPlay.js
src/plugin.js
src/register.js

Fixes a bug where the "registered middleware" log message would trigger after dispose/reinit even though middleware is not reregistered in this case.
Also fixes a bug where `initCancelContentPlay` would always be called if the debug setting was false. Not sure if this had functional consequences but it's clearly unintended.

fix: Middleware log message

---

src/states/BeforePreroll.js
test/unit/states/test.BeforePreroll.js

I thought this was needed, but it turned out to workaround a bug in my integration. Cleaning up the upstream.

fix: Remove hack in beforepreroll contentchanged handling

---

src/states/Preroll.js

On IE11, we can potentially receive a `play` event before `adBreak.end()` completes and thus before we set  `this.contentResuming = true;`.  This results in that `play` event being prefixed as an `ad-play` event since `contentResuming` is still `false` until after `end` completes.
This fix simply moves `this.contentResuming = true;` above the `AdBreak.end()` call which is in line with what we are also doing in `Midroll.js`.
Logically, this makes sense because we are adding the`vjs-ad-content-resuming` class to the player as a signal to the UI that we are done playing ads.
Tested on IE11 on Win7 and on Mac OS X Chrome 67.

set contentresuming before calling adBreak.end

---

src/plugin.js
src/states.js
src/states/AdsDone.js
src/states/BeforePreroll.js
src/states/ContentPlayback.js
src/states/Midroll.js
src/states/Postroll.js
src/states/Preroll.js
src/states/StitchedAdRoll.js
src/states/StitchedContentPlayback.js
src/states/abstract/AdState.js
src/states/abstract/ContentState.js
src/states/abstract/State.js
test/unit/states/abstract/test.AdState.js
test/unit/states/abstract/test.ContentState.js
test/unit/states/abstract/test.State.js
test/unit/states/test.AdsDone.js
test/unit/states/test.BeforePreroll.js
test/unit/states/test.ContentPlayback.js
test/unit/states/test.Midroll.js
test/unit/states/test.Postroll.js
test/unit/states/test.Preroll.js
test/unit/states/test.StitchedAdRoll.js
test/unit/states/test.StitchedContentPlayback.js

Currently there is a circular dependency issue that locks this repository to an old version of rollup, and thus an old version of the generator. This pull request seeks to remedy that. I implemented a registration system similar to what we have for Components in Video.js, but it will be for States here.

refactor: Add internal registration system for states to work around circular dependency issues.

---

src/states/Preroll.js
test/unit/states/test.Preroll.js

When using autoplay and receiving an `adserror` event, the `Preroll` state will cause an uncaught play promise exception and will never remove the `vjs-ads-loading` class, which can result a player that looks broken.

fix: Clean up player when a preroll fails and prevent uncaught play promise exceptions.

---

src/plugin.js

`playing` is an event that already exists in `VIDEO_EVENTS`, this may have caused us to fire two `playing` or `adplaying` events sometimes.

fix: Remove duplicate playing listener from redispatch.

---

src/register.js

I use contrib-ads to display ads in my player. 
Everything works pretty well but there is one irritating thing. 
Every time I load the page with the player and ads I see the following console message:
I manage to fix that changing the log level from 'info' to 'debug' for this specific message.
Do you have a different idea? how to resolve it.

Change log message level from 'info' to 'debug'.

---

src/plugin.js

Some techs, e.g. Flash may re-trigger `canplay` after playback has begun which can result in requesting playback when playback is already progressing. When assuming auto-play, playback should be requested only if it hasn't started. We also don't need to handle auto-playback for stitched ads because linear ads in such cases are stitched into the content.

Fix: on auto-play don't request playback for stitched ads as well as when playback already started

---

package-lock.json

There is one test here that fails on Video.js 7.5.x - see #488 - so this has been pinned to 7.4.x (though not in `package.json` so we do not change the actual dependency range).

chore(package): Update dependencies

---

package-lock.json
package.json
src/states/StitchedContentPlayback.js

This error was being thrown when the `contentchanged` event was fired when using stitched ads:
> TypeError: this._getName is not a function
Also, this updates lodash to fix audit issues.

fix: Fix an error being thrown when using changing sources with stitched ads scenarios

---

docs/integrator/macros.md
src/macros.js
test/integration/test.macros.js

Adds macros for player width and height. Uses the `player.current*` methods, as this is more relevant in an ad call than the configured dimensions.
Updates docs and tests.

feat: Add width and height macros

---

docs/integrator/macros.md
src/macros.js
test/integration/test.macros.js

Adds a `player.pageUrl` macro. This is intended as the URL at which the player has been embedded, whether directly or via an iframe. The name of the macro hopefully makes it clear that this is not an embed URL for the player itself.
If the player is in an iframe, this resolves to `document.referrer`, otherwise to `window.location.href`.
A test is only included for the iframe case for now, as the tests themselves run in an iframe.

feat: add pageUrl macro

---

docs/integrator/macros.md
src/macros.js
test/integration/test.macros.js

Adds `{playlistinfo.id}` and `{playlistinfo.name}` macros for ad targeting by playlist.

feat: Add playlistinfo macros

---

src/states/Preroll.js
test/integration/test.cancelContentPlay.js
test/unit/states/test.Preroll.js

**Problem Description**
When the Ads plugin throws an `adserror (Preroll)` due `AdError 1009: The VAST response document is empty` is getting stuck in the `Preroll` state and not switching to `ContentPlayback`  because of this behavior the Ads plugin is dispatching `timeupdate` as `contenttimeupdate`. So, in and `adserror` we want to transition to `ContentPlayback` with a `contentresumed` if the player is actually playing content.

fix: Ad plugin stuck in Preroll when adserror due empty VAST

---

docs/integrator/macros.md
src/macros.js
src/plugin.js
src/tcf.js
test/integration/test.macros.js

Adds support for consent string and other TCF metadata generated by a consent management platform for GDPR.
This will add a macro for any property of the [tcData object](https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/TCFv2/IAB%20Tech%20Lab%20-%20CMP%20API%20v2.md#tcdata). Most notable are `{tcf.gdprApplies}` and `{tcf.tcString}` which return whether GDPR applies to the session (broadly, is the browser in Europe) and the current consent string. Additionally `{tcf.gdprAppliesInt}` returns`{tcf.gdprApplies}` as an int, as this seems more commonly expected by ad servers. 
Updated docs, added tests. A demo page with a CMP is at https://consent.misterben.me/vjs.html

Add TCF macro support

---

.nvmrc

Update .nvmrc to use node 12 to prevent compatibility issues with node 14.

chore(nvmrc): Use erbium

---

test/integration/test.macros.js

New unit test for multiple, identical macro replacements in a string (for instance the serverUrl string). I.e.: `...&url={window.location.href}&description_url={window.location.href}...` using `ads.adMacroReplacement()`.

test: ad unit test for multiple identical macros

---

docs/integrator/options.md
src/plugin.js
src/states/BeforePreroll.js
test/unit/states/test.BeforePreroll.js

Video.js recently added new functionality for autoplay that triggers `autoplay-success` or `autoplay-failure` events depending on the result of the autoplay attempt. However, that functionality relies on the initial play promise being resolved/rejected naturally, so it is not compatible with the contrib-ads `callPlay()` middleware which terminates the first play request.
This PR adds an option to bypass that play termination if the player intends to autoplay. It does this by conditionally setting `_shouldBlockPlay` to `false` in the `BeforePreroll` state if the option is `true` and `player.autoplay()` is truthy.

feat: Add `allowVjsAutoplay` option to add support for custom video.js autoplay settings

---

docs/integrator/macros.md
src/macros.js
test/integration/test.macros.js

1. Allows an empty string to be default value for a macro, eg. `{pageVariable.mightBeThere=}`
2. Adds versions of the duration and player size macros which always return an int
* `{player.widthInt}`
* `{player.heightInt}`
* `{player.durationInt}`
* `{mediainfo.durationInt}`

feat: Macro improvements

---

src/macros.js
test/integration/test.macros.js

Currently, a macro like `{pageVariable.foo.bar}` will cause an error if `foo` is not defined, as there's an attempt to access `foo.bar`.
Adds a check for whether each level is defined within the pageVariable string replacement.

fix: Don't break on nested macros with undefined parent

---

docs/integrator/api.md
docs/integrator/common-interface.md
src/plugin.js
src/states/abstract/State.js
test/unit/states/abstract/test.State.js

Provide initial scaffolding for an `ads-ad-skipped` event, add associated state method, update tests, and add a description of the event to the Common Interface section of the Integrators documentation for guidance.
**Notes**
- `onAdSkipped()` currently has no functional effect on the ad/content lifecycle and its description has not been added to the API doc.
- The `player.ads.pod` object is used by several ad plugins already as part of an ad-skip workflow in the wild. It has been added to the Common Interfaces page for standardization and because a skip workflow would require information about not only an individual ad but also its order in a pod/break.

feat: Standardize ads-ad-skipped event

---

docs/integrator/macros.md
src/macros.js
src/plugin.js
src/usPrivacy.js
test/integration/test.macros.js
test/unit/test.usPrivacy.js

This PR adds support for a `{usp.uspString}` macro that is replaced with the US Privacy consent string, which is acquired using the IAB's [USP API](https://github.com/InteractiveAdvertisingBureau/USPrivacy/blob/master/CCPA/USP%20API.md) if it is available. The implementation follows the [reference code](https://github.com/InteractiveAdvertisingBureau/CCPA-reference-code) from IAB--  the API is invoked directly if it is available in the same window as the player, or via `postMessage()` if in a parent window. This also follows the same basic pattern as our implementation of TCF in this plugin, with a key difference. TCF triggers an event whenever the consent string changes, which lets us easily keep the string updated. The USP API does not, and manual asynchronous API calls are necessary to …

feat: Add support for US Privacy macro for CCPA compliance

---

docs/integrator/macros.md
src/macros.js
test/integration/test.macros.js

This PR does two things:
- Adds support for replacing multiple macros that match a regular expression (see full description in readme changes)
- Simplifies and fixes a design flaw in the macro name override logic, specifically for pageVariable macros

feat: Add support for regex macros

---

docs/integrator/macros.md
src/usPrivacy.js
test/unit/test.usPrivacy.js

`player.ads.updateUsPrivacyString(callback)` would not invoke the callback if the USP API was not present in the current window or any parent window. Now it is synchronously invoked with a `null` privacyString, so `updateUsPrivacyString()` can be used safely when the presence of the USP API is uncertain.

fix: updateUsPrivacyString() callback not invoked when USP API not in use in any window

---

src/usPrivacy.js

Integrations where the video.js player is in an iframe with a different origin are throwing errors when `findUspApiLocatorWindow` attempts to locate an ancestor frame with `ancestor.frames.__uspapiLocator`. 
No error is thown: 
* if the ancestor is same origin and a `__uspapiLocator` frame does not exist
* if the ancestor is not same origin but a `__uspapiLocator` locator frame exists
To remedy, we can wrap attempts to read `ancestorFrame.__uspapiLocator` in a try / catch. There is no need to handle the error as 
a) we'd expect to run into this while traversing multiple cross domain ancestors and 
b) if we don't find one in the top window, it probably just means there's no CMP. Users can't control whether this runs or not, so a warning or error would just be clutter.

fix: suppress errors while looking for `__uspapiLocator`

---

src/snapshot.js
test/integration/test.snapshot.js

Problem:  `restorePlayerSnapshot` uses `autoplay(true)` to force a content load in iOS Safari for correct placement of the playhead after an ad break. However if an integration has set `normalizeAutoplay: true` in the setup of `videojs`, `autoplay()` hands off to an async, programatic  play request with `manualAutoplay('play')`. The subsequent seek-back causes a visible restart of the content after ~1 second of playback. 
Solution: We can avoid the visual glitch by toggling autoplay directly on the HTML5 tech.  The existing followup mechanism to clear out the autoplay status continues to work as expected as `autoplay(false)` is passed to the tech anyway.

fix: Toggle autoplay directly on tech when restoring snapshot for iOS

---

src/adBreak.js

Contrib-ads attempts to mute the player behind the ad for stitched ads and this causes all ads to play muted. Proposed fix is to add a check (`!player.ads.settings.stitchedAds`)for stitched ads before muting the player.

fix: muted Ads

---

src/plugin.scss

Update contrib-ads implementation of the loading spinner component style to accommodate changes in videojs v8.11.x that cause a misalignment of the spinner segment animation before ad playback:
The contrib-ads implementation of an ad-specific spinner requires inherited rules from videojs and also a number of lines that were identical to videojs but became out of sync with recent updates. The inconsistency caused a minor visual defect, specifically because contrib-ads used `display: block` to make the spinner appear.
Fix parameters:
1.  Update `.vjs-ad-loading .vjs-loading-spinner` style to include `display:flex` and expected justify/alignment rules to center the spinner segment pseudo-elements, to match changes from videojs.
2. Remove outdated css animation fallbacks to match videojs
3. …

fix: Ad loading spinner animation misalignment

---

src/consts/errors.js
src/macros.js
src/plugin.js
src/snapshot.js
src/states/BeforePreroll.js
src/states/Midroll.js
src/states/Postroll.js
src/states/Preroll.js

Quick update to add errors to this plugin. They will be removed from the video.js repo.

chore: move ad errors from videojs
